sudo: required
language: node_js
node_js:
  - "10"
cache:
  yarn: true
script: yarn qa
before_deploy:
  - sudo python -m pip install awscli==1.14.7
deploy:
  # deploy to the staging environment
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh test
    on:
      branch: master
  # deploy to production
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh prod
    on:
      branch: deploy
