sudo: required
language: node_js
node_js:
  - "8"
cache:
  yarn: true
  directories:
    - node_modules
script: yarn qa
after_success:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - aws iam get-user
  - eval $(aws ecr get-login --region us-central-1)
  - make deploy.test
