sudo: required
language: node_js
node_js:
  - "8"
cache:
  yarn: true
script: yarn qa
before_deploy:
  - sudo python -m pip install awscli==1.14.7
deploy:
  # deploy develop to the staging environment
  - provider: script
    script: bash scripts/deploy.sh test
    on:
      branch: develop
  # deploy master to production
  - provider: script
    script: bash scripts/deploy.sh prod
    on:
      branch: master
