sudo: required
language: node_js
node_js:
  - "8"
cache:
  yarn: true
  directories:
    - node_modules
services:
  - docker
script: yarn qa
after_success:
  - docker --version
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - eval $(aws ecr get-login --region us-east-1)
  - make deploy.test
